# Numpy

NumPy, (Numerical Python), is a library used for mathematical and logical operations on arrays.  Here we will discusses in brief about the various array functions, types of indexing.

**Importing numpy library**

In [1]:
import numpy as np

### Numpy Array

**1-D array or vectors**

In [3]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

**2-D array or matrices**

In [4]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#Cheak the dimension of an array, using shape function
np.shape(arr)

(2, 3)

**arange(start,stop,step)**

arange() returns an ndarray object containing evenly spaced values within a defined interval. 

In [7]:
#Create an array (1x10), with a step of 1. 
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#Convert 1x10 matrix to 2x5 using reshape()
arr = arr.reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**Zero(shape)**

Shape = (rows,columns)

In [12]:
#Create an array (1x5) of 0 value.
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

**ones(shape)**

In [15]:
#Create an array (2x2) of 1.
arr = np.ones((2,2))
arr

array([[1., 1.],
       [1., 1.]])

# **linspace()**

The linspace() function returns number spaces evenly w.r.t interval. Similar to arange() but instead of step it uses sample number.

In [17]:
#Create an array (1x5) from 1 to 3 using 5 samples.
arr = np.linspace(start = 1,stop = 3,num = 5)
arr

array([1. , 1.5, 2. , 2.5, 3. ])

## Random

NumPy offers the random module to work with random numbers.

In [18]:
#Import random module
import numpy.random as random

**randint()**

It gives a int value between the specified interval. 

In [19]:
random.randint(98,100)

98

In [22]:
#Generate a 2-D array with 3 rows, each row containing 5 random integers from 10 to 100:
arr = random.randint(low=10,high=100,size=(2,3))
arr

array([[73, 89, 32],
       [40, 45, 75]])

**rand()**

It gives random float value between 0 and 1.

In [23]:
arr = random.rand(2)
arr

array([0.41354944, 0.67324183])

In [25]:
#Generate a 2-D array with 3 rows, each row containing 5 random numbers
arr = random.rand(2,3)
arr

array([[0.67020515, 0.23446322, 0.28909727],
       [0.03426622, 0.69379172, 0.95759219]])

### Numpy Operations

**concatination()**

This function is used to join two or more arrays of the same shape along a specified axis.

In [29]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 
arr = np.concatenate((a,b))
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

**vstack()**

It will append data vertically

In [30]:
arr = np.vstack((a,b))
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

**hstack()**

It will append data horizontally

In [31]:
arr = np.hstack((a,b))
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Statistical Functions

**max() min()**

In [33]:
#Generate a 1-D array from 0 to 9, using arange()
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
#get min and max value of above array
a = np.min(arr)
b = np.max(arr)
print(f"{a}\n{b}")

0
9


**mean() median() std()** 

In [37]:
#Mean of array "arr"
np.mean(arr)

4.5

In [39]:
#Standard deviation of array "arr"
np.std(arr)

2.8722813232690143

In [40]:
#Median of array "arr"
np.median(arr)

4.5